[tool.poetry]
name = "cob-core"
version = "0.1.0"
description = ""
authors = ["Marcin Baryłka <marcin.barylka@gmail.com>"]
readme = "README.md"
packages = [{include = "cob"}]

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
